"""initial schema

Revision ID: 3fd22d8de190
Revises: 
Create Date: 2026-08-31 23:30:03.565685

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '3fd22d8de190'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 启用 pgvector 扩展（幂等）：本迁移使用 vector 类型与 hnsw 索引，
    # 在迁移内确保扩展存在，避免只依赖 Compose db-init 脚本或人工初始化
    # （CI 的 PostgreSQL service 不会挂载 docker/db-init 目录）。
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('alert',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('warehouse_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('blocker_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('open','closed')", name='ck_alert_status_enum'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_wh_product', 'alert', ['warehouse_id', 'product_id'], unique=False)
    op.create_index('uq_alert_open_dedupe', 'alert', ['warehouse_id', 'product_id', 'blocker_code'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_operation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_time', 'audit_log', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_table('document',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_type in ('replenishment_policy','safety_stock','warehouse_rule','supplier_constraint','receiving_sop')", name='ck_document_type_enum'),
    sa.CheckConstraint('effective_to IS NULL OR effective_from <= effective_to', name='ck_document_effective_range'),
    sa.CheckConstraint('version >= 1', name='ck_document_version_pos'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_doc_type'), 'document', ['doc_type'], unique=False)
    op.create_table('execution',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('schedule_id', sa.String(length=64), nullable=True),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scanned_count', sa.Integer(), nullable=False),
    sa.Column('draft_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('triggered_by_actor_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('running','succeeded','failed','partial')", name='ck_execution_status_enum'),
    sa.CheckConstraint("trigger_type in ('scheduled','manual','rerun')", name='ck_execution_trigger_enum'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'scheduled_at', name='uq_execution_schedule_time')
    )
    op.create_index('ix_execution_schedule', 'execution', ['schedule_id'], unique=False)
    op.create_table('idempotency_operation',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.String(length=64), nullable=False),
    sa.Column('command_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_ref', sa.String(length=256), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('hash_schema_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('in_progress','retryable','succeeded','failed','unknown')", name='ck_idem_op_status_enum'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'command_type', 'aggregate_ref', 'idempotency_key', name='uq_idem_op_scope_key')
    )
    op.create_index('ix_idem_op_entity', 'idempotency_operation', ['entity_type', 'entity_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('basic_unit', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.create_table('receipt_event',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('receipt_event_id', sa.String(length=128), nullable=False),
    sa.Column('purchase_order_line_id', sa.String(length=64), nullable=False),
    sa.Column('warehouse_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('hash_schema_version', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty > 0', name='ck_receipt_qty_pos'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_event_id', name='uq_receipt_event_id')
    )
    op.create_index(op.f('ix_receipt_event_purchase_order_line_id'), 'receipt_event', ['purchase_order_line_id'], unique=False)
    op.create_table('replenishment_rule',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_product_id', sa.String(length=64), nullable=True),
    sa.Column('scope_category', sa.String(length=128), nullable=True),
    sa.Column('scope_warehouse_id', sa.String(length=64), nullable=True),
    sa.Column('safety_stock', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('review_period_days', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source_document_id', sa.String(length=64), nullable=False),
    sa.Column('source_chunk_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope in ('product','category','warehouse','global')", name='ck_rule_scope_enum'),
    sa.CheckConstraint('review_period_days >= 0', name='ck_rule_review_days_nonneg'),
    sa.CheckConstraint('safety_stock >= 0', name='ck_rule_safety_stock_nonneg'),
    sa.CheckConstraint('version >= 1', name='ck_rule_version_pos'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replenishment_rule_code'), 'replenishment_rule', ['code'], unique=False)
    op.create_index(op.f('ix_replenishment_rule_rule_type'), 'replenishment_rule', ['rule_type'], unique=False)
    op.create_index('ix_rule_scope_apply', 'replenishment_rule', ['scope', 'enabled', 'effective_from'], unique=False)
    op.create_table('rule_source',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('source_document_id', sa.String(length=64), nullable=False),
    sa.Column('source_chunk_id', sa.String(length=128), nullable=False),
    sa.Column('extracted_params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'source_chunk_id', name='uq_rule_source_chunk')
    )
    op.create_index(op.f('ix_rule_source_rule_id'), 'rule_source', ['rule_id'], unique=False)
    op.create_table('schedule',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cron_expr', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('default_window', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_window in (7,14,30)', name='ck_schedule_window'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('business_priority', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String(length=16)), nullable=False),
    sa.CheckConstraint("roles <@ ARRAY['operator','approver','buyer','system','admin']::varchar[]", name='ck_user_roles_enum'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_resume',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('decision_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('hash_schema_version', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('pending','succeeded','failed')", name='ck_workflow_resume_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'plan_id', 'decision_version', name='uq_workflow_resume_key')
    )
    op.create_table('chunk',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.CheckConstraint('seq_no >= 1', name='ck_chunk_seq_pos'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'seq_no', name='uq_chunk_doc_seq')
    )
    op.create_index(op.f('ix_chunk_document_id'), 'chunk', ['document_id'], unique=False)
    op.create_index('ix_chunk_fts', 'chunk', [sa.literal_column("to_tsvector('simple', search_text)")], unique=False, postgresql_using='gin')
    op.create_table('demand_day',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('warehouse_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('demand', sa.BigInteger(), nullable=False),
    sa.Column('source_complete', sa.Boolean(), nullable=False),
    sa.CheckConstraint('demand >= 0', name='ck_demand_day_nonneg'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', 'day', name='uq_demand_day_wh_product_day')
    )
    op.create_index(op.f('ix_demand_day_product_id'), 'demand_day', ['product_id'], unique=False)
    op.create_index(op.f('ix_demand_day_warehouse_id'), 'demand_day', ['warehouse_id'], unique=False)
    op.create_index('ix_demand_day_wh_product', 'demand_day', ['warehouse_id', 'product_id'], unique=False)
    op.create_table('execution_item',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('warehouse_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('plan_line_id', sa.String(length=64), nullable=True),
    sa.Column('alert_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('success','blocked','failed')", name='ck_exec_item_status_enum'),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'warehouse_id', 'product_id', name='uq_exec_item_wh_product')
    )
    op.create_index('ix_exec_item_execution', 'execution_item', ['execution_id'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('warehouse_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_warehouse_id'), 'location', ['warehouse_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_table('purchase_order',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('warehouse_id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('supplier_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency = 'CNY'", name='ck_po_currency_cny'),
    sa.CheckConstraint("status in ('po_created','ordering','ordered','order_unknown','partially_received','received','closed','cancelled')", name='ck_po_status_enum'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_po_plan', 'purchase_order', ['plan_id'], unique=False)
    op.create_index('ix_po_supplier_status', 'purchase_order', ['supplier_id', 'status'], unique=False)
    op.create_index(op.f('ix_purchase_order_warehouse_id'), 'purchase_order', ['warehouse_id'], unique=False)
    op.create_table('replenishment_plan',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('warehouse_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_window', sa.Integer(), nullable=False),
    sa.Column('planning_date', sa.Date(), nullable=False),
    sa.Column('revision_of_plan_id', sa.String(length=64), nullable=True),
    sa.Column('decision_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('draft','pending_approval','approved','rejected','superseded')", name='ck_plan_status_enum'),
    sa.CheckConstraint('requested_window in (7,14,30)', name='ck_plan_requested_window_enum'),
    sa.ForeignKeyConstraint(['revision_of_plan_id'], ['replenishment_plan.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replenishment_plan_thread_id'), 'replenishment_plan', ['thread_id'], unique=False)
    op.create_index(op.f('ix_replenishment_plan_warehouse_id'), 'replenishment_plan', ['warehouse_id'], unique=False)
    op.create_table('supplier_product',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('business_priority', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=2), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.Column('minimum_order_qty', sa.Integer(), nullable=False),
    sa.Column('pack_multiple', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_from <= effective_to', name='ck_sp_effective_range'),
    sa.CheckConstraint('lead_days >= 0', name='ck_sp_lead_days_nonneg'),
    sa.CheckConstraint('minimum_order_qty >= 0', name='ck_sp_min_qty_nonneg'),
    sa.CheckConstraint('pack_multiple > 0', name='ck_sp_pack_multiple_pos'),
    sa.CheckConstraint('price >= 0', name='ck_sp_price_nonneg'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'product_id', name='uq_supplier_product')
    )
    op.create_index(op.f('ix_supplier_product_product_id'), 'supplier_product', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_product_supplier_id'), 'supplier_product', ['supplier_id'], unique=False)
    op.create_table('chunk_embedding',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', name='uq_chunk_embedding_chunk')
    )
    op.create_index('ix_chunk_embedding_vector', 'chunk_embedding', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('lot',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.String(length=64), nullable=False),
    sa.Column('batch_no', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_product_id'), 'lot', ['product_id'], unique=False)
    op.create_table('plan_line',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('warehouse_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('flag', sa.String(length=16), nullable=False),
    sa.Column('active_for_dedupe', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=512), nullable=True),
    sa.Column('blocked_code', sa.String(length=64), nullable=True),
    sa.Column('blocked_reason', sa.String(length=1024), nullable=True),
    sa.Column('daily_forecast', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('forecast_algorithm', sa.String(length=32), nullable=True),
    sa.Column('mae', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('wape', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('fallback_reason', sa.String(length=256), nullable=True),
    sa.Column('planning_window', sa.Integer(), nullable=False),
    sa.Column('coverage_demand', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('target_stock', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('available', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('inbound', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('net_demand', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('order_qty', sa.BigInteger(), nullable=False),
    sa.Column('fixed_safety_stock', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.Column('review_period_days', sa.Integer(), nullable=False),
    sa.Column('minimum_order_qty', sa.Integer(), nullable=False),
    sa.Column('pack_multiple', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.String(length=64), nullable=True),
    sa.Column('supplier_reason', sa.String(length=1024), nullable=True),
    sa.Column('on_hand', sa.BigInteger(), nullable=False),
    sa.Column('reserved', sa.BigInteger(), nullable=False),
    sa.Column('decision_input_hash', sa.String(length=64), nullable=False),
    sa.Column('hash_schema_version', sa.String(length=64), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('intermediate', sa.JSON(), nullable=False),
    sa.Column('rule_refs', sa.JSON(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=64), nullable=False),
    sa.Column('demand_cutoff_date', sa.Date(), nullable=True),
    sa.Column('quant_version', sa.Integer(), nullable=True),
    sa.Column('supplier_rel_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("flag in ('valid','excluded','blocked')", name='ck_plan_line_flag_enum'),
    sa.CheckConstraint('lead_days >= 0', name='ck_plan_line_lead_days_nonneg'),
    sa.CheckConstraint('minimum_order_qty >= 0', name='ck_plan_line_min_qty_nonneg'),
    sa.CheckConstraint('on_hand >= 0', name='ck_plan_line_on_hand_nonneg'),
    sa.CheckConstraint('order_qty >= 0', name='ck_plan_line_order_qty_nonneg'),
    sa.CheckConstraint('pack_multiple > 0', name='ck_plan_line_pack_multiple_pos'),
    sa.CheckConstraint('planning_window >= 0', name='ck_plan_line_window_nonneg'),
    sa.CheckConstraint('reserved <= on_hand', name='ck_plan_line_reserved_le_on_hand'),
    sa.CheckConstraint('reserved >= 0', name='ck_plan_line_reserved_nonneg'),
    sa.CheckConstraint('review_period_days >= 0', name='ck_plan_line_review_days_nonneg'),
    sa.ForeignKeyConstraint(['plan_id'], ['replenishment_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'product_id', name='uq_plan_line_product')
    )
    op.create_index('ix_plan_line_plan', 'plan_line', ['plan_id'], unique=False)
    op.create_index('ix_plan_line_wh_product', 'plan_line', ['warehouse_id', 'product_id'], unique=False)
    op.create_index('uq_plan_line_active_dedupe', 'plan_line', ['warehouse_id', 'product_id'], unique=True, postgresql_where=sa.text('active_for_dedupe'))
    op.create_table('purchase_order_attempt',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('internal_idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('supplier_idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('hash_schema_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('external_order_no', sa.String(length=128), nullable=True),
    sa.Column('response_summary', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('attempting','succeeded','failed','unknown','queried_created','queried_not_found')", name='ck_attempt_status_enum'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id', 'attempt_no', name='uq_po_attempt_no'),
    sa.UniqueConstraint('supplier_idempotency_key', name='uq_po_attempt_supplier_key')
    )
    op.create_index('ix_attempt_po', 'purchase_order_attempt', ['purchase_order_id'], unique=False)
    op.create_index('ix_attempt_status', 'purchase_order_attempt', ['status'], unique=False)
    op.create_table('purchase_order_line',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=64), nullable=False),
    sa.Column('plan_line_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('order_qty', sa.BigInteger(), nullable=False),
    sa.Column('received_qty', sa.BigInteger(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=28, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('order_qty >= 0', name='ck_po_line_qty_nonneg'),
    sa.CheckConstraint('received_qty <= order_qty', name='ck_po_line_received_le_order'),
    sa.CheckConstraint('received_qty >= 0', name='ck_po_line_received_nonneg'),
    sa.CheckConstraint('unit_price >= 0', name='ck_po_line_price_nonneg'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_line_id', name='uq_po_line_plan_line')
    )
    op.create_index('ix_po_line_po', 'purchase_order_line', ['purchase_order_id'], unique=False)
    op.create_table('quant',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('warehouse_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.String(length=64), nullable=False),
    sa.Column('lot_id', sa.String(length=64), nullable=False),
    sa.Column('on_hand', sa.BigInteger(), nullable=False),
    sa.Column('reserved', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('on_hand >= 0', name='ck_quant_on_hand_nonneg'),
    sa.CheckConstraint('reserved <= on_hand', name='ck_quant_reserved_le_on_hand'),
    sa.CheckConstraint('reserved >= 0', name='ck_quant_reserved_nonneg'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', 'location_id', 'lot_id', name='uq_quant_cell')
    )
    op.create_index(op.f('ix_quant_product_id'), 'quant', ['product_id'], unique=False)
    op.create_index(op.f('ix_quant_warehouse_id'), 'quant', ['warehouse_id'], unique=False)
    op.create_index('ix_quant_wh_product', 'quant', ['warehouse_id', 'product_id'], unique=False)
    op.create_table('stock_move',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('warehouse_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.String(length=64), nullable=False),
    sa.Column('lot_id', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('move_type', sa.String(length=32), nullable=False),
    sa.Column('ref_type', sa.String(length=64), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=False),
    sa.Column('receipt_event_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty != 0', name='ck_stock_move_qty_nonzero'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_move_product_id'), 'stock_move', ['product_id'], unique=False)
    op.create_index('ix_stock_move_ref', 'stock_move', ['ref_type', 'ref_id'], unique=False)
    op.create_index(op.f('ix_stock_move_warehouse_id'), 'stock_move', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_move_warehouse_id'), table_name='stock_move')
    op.drop_index('ix_stock_move_ref', table_name='stock_move')
    op.drop_index(op.f('ix_stock_move_product_id'), table_name='stock_move')
    op.drop_table('stock_move')
    op.drop_index('ix_quant_wh_product', table_name='quant')
    op.drop_index(op.f('ix_quant_warehouse_id'), table_name='quant')
    op.drop_index(op.f('ix_quant_product_id'), table_name='quant')
    op.drop_table('quant')
    op.drop_index('ix_po_line_po', table_name='purchase_order_line')
    op.drop_table('purchase_order_line')
    op.drop_index('ix_attempt_status', table_name='purchase_order_attempt')
    op.drop_index('ix_attempt_po', table_name='purchase_order_attempt')
    op.drop_table('purchase_order_attempt')
    op.drop_index('uq_plan_line_active_dedupe', table_name='plan_line', postgresql_where=sa.text('active_for_dedupe'))
    op.drop_index('ix_plan_line_wh_product', table_name='plan_line')
    op.drop_index('ix_plan_line_plan', table_name='plan_line')
    op.drop_table('plan_line')
    op.drop_index(op.f('ix_lot_product_id'), table_name='lot')
    op.drop_table('lot')
    op.drop_index('ix_chunk_embedding_vector', table_name='chunk_embedding', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('chunk_embedding')
    op.drop_index(op.f('ix_supplier_product_supplier_id'), table_name='supplier_product')
    op.drop_index(op.f('ix_supplier_product_product_id'), table_name='supplier_product')
    op.drop_table('supplier_product')
    op.drop_index(op.f('ix_replenishment_plan_warehouse_id'), table_name='replenishment_plan')
    op.drop_index(op.f('ix_replenishment_plan_thread_id'), table_name='replenishment_plan')
    op.drop_table('replenishment_plan')
    op.drop_index(op.f('ix_purchase_order_warehouse_id'), table_name='purchase_order')
    op.drop_index('ix_po_supplier_status', table_name='purchase_order')
    op.drop_index('ix_po_plan', table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_location_warehouse_id'), table_name='location')
    op.drop_table('location')
    op.drop_index('ix_exec_item_execution', table_name='execution_item')
    op.drop_table('execution_item')
    op.drop_index('ix_demand_day_wh_product', table_name='demand_day')
    op.drop_index(op.f('ix_demand_day_warehouse_id'), table_name='demand_day')
    op.drop_index(op.f('ix_demand_day_product_id'), table_name='demand_day')
    op.drop_table('demand_day')
    op.drop_index('ix_chunk_fts', table_name='chunk', postgresql_using='gin')
    op.drop_index(op.f('ix_chunk_document_id'), table_name='chunk')
    op.drop_table('chunk')
    op.drop_table('workflow_resume')
    op.drop_table('warehouse')
    op.drop_table('user')
    op.drop_table('supplier')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_rule_source_rule_id'), table_name='rule_source')
    op.drop_table('rule_source')
    op.drop_index('ix_rule_scope_apply', table_name='replenishment_rule')
    op.drop_index(op.f('ix_replenishment_rule_rule_type'), table_name='replenishment_rule')
    op.drop_index(op.f('ix_replenishment_rule_code'), table_name='replenishment_rule')
    op.drop_table('replenishment_rule')
    op.drop_index(op.f('ix_receipt_event_purchase_order_line_id'), table_name='receipt_event')
    op.drop_table('receipt_event')
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_table('product')
    op.drop_index('ix_idem_op_entity', table_name='idempotency_operation')
    op.drop_table('idempotency_operation')
    op.drop_index('ix_execution_schedule', table_name='execution')
    op.drop_table('execution')
    op.drop_index(op.f('ix_document_doc_type'), table_name='document')
    op.drop_table('document')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('ix_audit_actor_time', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('uq_alert_open_dedupe', table_name='alert', postgresql_where=sa.text("status = 'open'"))
    op.drop_index('ix_alert_wh_product', table_name='alert')
    op.drop_table('alert')
    # ### end Alembic commands ###
